# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY . .

# COPY pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Copy specific app and libs directories
COPY apps/gateway ./apps/gateway

RUN pnpm install @nestjs/cli nodemon

RUN pnpm build gateway

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run the app
CMD ["npx", "nodemon", "start:dev", "gateway"]
