name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull fajarspace/proposals-services-api-gateway:latest
      - name: Delete old docker container
        run: sudo docker rm -f proposals-services-api-gateway-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:4002 --name proposals-services-api-gateway-container fajarspace/proposals-services-api-gateway
